name: Terraform CI

on:
  pull_request:
    branches: [ main, develop, 'release/**' ]
    paths:
      - '**.tf'
      - '**.tfvars'
      - '.github/workflows/terraform-ci.yml'
  push:
    branches: [ main, develop ]
    paths:
      - '**.tf'
      - '**.tfvars'

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        terraform-version: ['1.6.x', '1.7.x']
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ matrix.terraform-version }}
    
    - name: Terraform Format Check
      run: terraform fmt -check -recursive
    
    - name: Terraform Init
      run: terraform init -backend=false
    
    - name: Terraform Validate
      run: terraform validate
    
    - name: Run tflint
      uses: terraform-linters/setup-tflint@v4
      with:
        tflint_version: latest
    
    - name: Init tflint
      run: tflint --init
    
    - name: Run tflint
      run: tflint --recursive
    
    - name: Run Checkov security scan
      uses: bridgecrewio/checkov-action@master
      with:
        directory: .
        framework: terraform
        soft_fail: true  # Set to false once initial issues are fixed
        output_format: cli
        download_external_modules: true
    
    - name: Terraform Plan (if applicable)
      if: github.event_name == 'pull_request'
      run: |
        terraform plan -no-color -input=false
      continue-on-error: true  # May fail without AWS credentials
      env:
        # Add necessary AWS credentials or backend config
        TF_IN_AUTOMATION: true
    
    - name: Comment PR with Plan
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      continue-on-error: true
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
          #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
          
          *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: output
          })
